version: '2'

services:

  ## MongoDB

  primary:
    image: mongo:3.0
    hostname: primary
    command:
    - mongod
    - --replSet
    - mgoExporterSet
    volumes:
    - primary-db:/data/db
    - primary-configdb:/data/configdb
    ports:
    - "30001:27017"

  fallback:
    image: mongo:3.0
    hostname: fallback
    command:
    - mongod
    - --replSet
    - mgoExporterSet
    volumes:
    - fallback-db:/data/db
    - fallback-configdb:/data/configdb
    ports:
    - "30002:27017"

  secondary:
    image: mongo:3.0
    hostname: secondary
    command:
    - mongod
    - --replSet
    - mgoExporterSet
    volumes:
    - secondary-db:/data/db
    - secondary-configdb:/data/configdb
    ports:
    - "30003:27017"

  provision-replicaset:
    image: mongo:3.0
    command:
    - /opt/provision/mongodb.sh
    volumes:
    - ./docker/compose:/opt/provision:ro
    depends_on:
    - primary
    - secondary
    - fallback
    restart: "no"

  ## mgo-exporter

  exporter-primary:
    build: .
    image: blippar/mgo-exporter
    command:
      - --forwarder
      - logstash://logstash:2000
      - --repl
      - mgoExporterSet
      - primary:27017
      - test
      - collection
    restart: on-failure
    depends_on:
    - logstash
    - primary

  exporter-fallback:
    build: .
    image: blippar/mgo-exporter
    command:
      - --forwarder
      - logstash://logstash:2000
      - --repl
      - mgoExporterSet
      - fallback:27017
      - test
      - collection
    restart: on-failure
    depends_on:
    - logstash
    - fallback

  exporter-secondary:
    build: .
    image: blippar/mgo-exporter
    command:
      - --forwarder
      - logstash://logstash:2000
      - --repl
      - mgoExporterSet
      - secondary:27017
      - test
      - collection
    restart: on-failure
    depends_on:
    - logstash
    - secondary

  ## ELK

  elastic:
    image: blacktop/elasticsearch:5.4
    environment:
      cluster.name: mgo-exporter
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
    - "9200:9200"
    volumes:
    - elastic-data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:5.4
    command:
    - logstash
    - -f
    - /usr/share/logstash/config/config.conf
    volumes:
    - ./docker/logstash:/usr/share/logstash/config:ro
    ports:
    - "2000:2000"
    depends_on:
    - elastic

  kibana:
    image: kibana:5.4
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
    ports:
    - "5601:5601"
    depends_on:
    - elastic

  provision-kibana:
    image: endeveit/docker-jq
    command:
    - /opt/provision/kibana.sh
    volumes:
    - ./docker/kibana:/opt/kibana:ro
    - ./docker/compose:/opt/provision:ro
    depends_on:
    - elastic
    - kibana
    restart: "no"

volumes:
  primary-db:
  primary-configdb:
  fallback-db:
  fallback-configdb:
  secondary-db:
  secondary-configdb:
  solo-db:
  solo-configdb:
  elastic-data:
